name: Netlify Document Staging Environment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  publishMasterCommit:
    name: Deploying on Netlify Document Staging Environment
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.action == 'closed' && github.event.pull_request.merged == 'true')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm ci
        working-directory: docs/document
      - name: Build document
        run: npm run build
        working-directory: docs/document
      - name: Install Netlify
        run: npm i netlify-cli@9 --no-save
      - name: Deploy
        run: netlify deploy --dir=./docs/document/build --alias=staging --auth=${{ secrets.NETLIFY_AUTH_TOKEN }} --site=${{ secrets.NETLIFY_DOCUMENT_ID }}
      - name: Status check
        uses: Sibz/github-status-action@v1.1.1
        with:
          authToken: ${{ secrets.WORKFLOW_TOKEN }}
          context: Netlify preview
          state: success
          target_url: https://staging--kuc-docusaurus-v2.netlify.app